### ISSUE TITLE
[Bug]: Pavucontrol SEGFAULT

### ISSUE THREAD

**Issue by iiztp** [iiztp/hyprdots#5]
### Description

When launching pavucontrol, it segfaults.

```bash
❯ pavucontrol

(pavucontrol:22918): Gtk-WARNING **: 10:27:01.818: Theme parser error: gtk.css:5625:3-9: No property named "height"

(pavucontrol:22918): Gtk-WARNING **: 10:27:01.831: Theme parser error: gtk.css:5625:3-9: No property named "height"
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
fish: Job 1, 'pavucontrol' terminated by signal SIGSEGV (Address boundary error)
```
After further investigation with gdb, it's a problem with the wayland protocol.

```bash
Thread 1 "pavucontrol" received signal SIGSEGV, Segmentation fault.
0x00007fffc6a6a87d in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_intel.so
(gdb) backtrace
#0  0x00007fffc6a6a87d in ??? () at /usr/lib/x86_64-linux-gnu/libvulkan_intel.so
#1  0x00007ffff6ef2a79 in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#2  0x00007ffff6ef3208 in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#3  0x00007ffff6ee8828 in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#4  0x00007ffff6e75129 in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#5  0x00007ffff57bd3fe in ??? () at /lib/x86_64-linux-gnu/libffi.so.8
#6  0x00007ffff57bc70d in ??? () at /lib/x86_64-linux-gnu/libffi.so.8
#7  0x00007ffff57bcee3 in ffi_call () at /lib/x86_64-linux-gnu/libffi.so.8
#8  0x00007ffff6684cc1 in ??? () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#9  0x00007ffff6680c2f in ??? () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#10 0x00007ffff6681f33 in wl_display_dispatch_queue_pending () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#11 0x00007ffff6682c8f in wl_display_roundtrip_queue () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#12 0x00007ffff6e7f63d in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#13 0x00007ffff6ef3c37 in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#14 0x00007ffff688db13 in g_initable_new_valist () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007ffff688dbfa in g_initable_new () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#16 0x00007ffff6f2f2fc in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#17 0x00007ffff6f80f46 in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#18 0x00007ffff6f047e8 in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#19 0x00007ffff6f058f9 in gsk_renderer_new_for_surface () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#20 0x00007ffff6cce4d0 in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#21 0x000055555558dcb9 in ??? ()
#22 0x00007ffff7d41b7e in Gtk::Widget_Class::realize_callback(_GtkWidget*) () at /lib/x86_64-linux-gnu/libgtkmm-4.0.so.0
#23 0x00007ffff79b3bc9 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff79c98f8 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff79cf666 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff79cf723 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff6cc27df in gtk_widget_realize () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#28 0x00007ffff6cd42d1 in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#29 0x00007ffff7d419ab in Gtk::Widget_Class::show_callback(_GtkWidget*) () at /lib/x86_64-linux-gnu/libgtkmm-4.0.so.0
#30 0x00007ffff79b3bc9 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007ffff79c98f8 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff79cf666 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff79cf723 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff6cb83b0 in gtk_widget_show () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#35 0x00007ffff6ccccc0 in ??? () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#36 0x00007ffff770983b in Gio::Application_Class::activate_callback(_GApplication*) () at /lib/x86_64-linux-gnu/libgiomm-2.68.so.1
#37 0x00007ffff79b3bc9 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007ffff79c98f8 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#39 0x00007ffff79cf666 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#40 0x00007ffff79cf723 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#41 0x0000555555596caf in ??? ()
#42 0x00007ffff770c8c4 in ??? () at /lib/x86_64-linux-gnu/libgiomm-2.68.so.1
#43 0x00007ffff6894f6a in ??? () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#44 0x00007ffff79b39c0 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#45 0x00007ffff79c7d83 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007ffff79c9072 in ??? () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#47 0x00007ffff79cf666 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#48 0x00007ffff79cf723 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#49 0x00007ffff68f1b25 in ??? () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#50 0x00007ffff68f40aa in ??? () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#51 0x00007ffff77092bc in Gio::Application::local_command_line_vfunc(char**&, int&) () at /lib/x86_64-linux-gnu/libgiomm-2.68.so.1
#52 0x00007ffff7709521 in Gio::Application_Class::local_command_line_vfunc_callback(_GApplication*, char***, int*) () at /lib/x86_64-linux-gnu/libgiomm-2.68.so.1
#53 0x00007ffff68f4216 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#54 0x00007ffff623edba in __libc_start_call_main (main=main@entry=0x555555579f30 <main>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdfc8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#55 0x00007ffff623ee75 in __libc_start_main_impl
    (main=0x555555579f30 <main>, argc=1, argv=0x7fffffffdfc8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdfb8)
    at ../csu/libc-start.c:360
#56 0x000055555557a411 in ??? ()
```

As it is launched by libvulkan and libwayland-client.

### Steps to Reproduce

1. Launch pavucontrol

### Expected Behavior

Not segfault.

### Actual Behavior

Segfaults and crashes

### Environment

- Linux Distro: Debian SID
- Linux Version: Linux 6.10.10
- Hyprland Version: Commit 92df6b0dce1b81b130c2b0e46d206c8c3dbb2971
- Libwayland Version: 1.23.0-1
- Libvulkan1 Version: 1.3.290.0-1

### Additional Information
Temporary fix : Wherever you launch pavucontrol, you can force it to use x11 : `env -u WAYLAND_DISPLAY pavucontrol`

**Comment by iiztp** [comment]
After some upgrades, it works now.
